#!/bin/bash
# write an info entry to out log file
# Variante a:  $1 = log entry
# Variante b: $1= LogLevel, $2 log entry: Only if $1 is smaler or equal to the loglevel it will be reported
logInfo() {
  if [[ "$1" =~ ^[0-9]+$ ]] && [[ $# -ge 2 ]]; then # Attention: No single or double quotes for regExp allowed!
    ll=$1 # 1st parameter is log level
    shift
  else
    ll=1 # defaultvalue
  fi
  if [[ "$ll" -le  "$LOGLEVEL" ]]; then
	  /bin/echo -e "$(date "$DTFMT"): $*" | /bin/tee -a "$LOGFILE"
  fi
}

# write an error entry to out log file
#   $1 - log entry
logError() {
	/bin/echo "$(date "$DTFMT"): <span style=\"color:red;\">$*</span><br/>" | /bin/tee -a "$LOGFILE"
  # https://stackoverflow.com/questions/692000/how-do-i-write-standard-error-to-a-file-while-using-tee-with-a-pipe
 	# /bin/echo "$(date "$DTFMT"): <span style=\"color:red;\">$1</span><br/>" > >(tee -a stdout.log) 2> >(tee -a stderr.log >&2)
}


# set the led or send a beep
# https://kb.synology.com/de-de/DSM/tutorial/Overview_of_LED_indicator_statuses_during_bootup
#   $1 - event (see http://www.synology-wiki.de/index.php/LEDs_und_Buttons)
# 1 	0x31 	power off
# 2 	0x32 	kurzer Pieps-Ton
# 3 	0x33 	langer Pieps-Ton
# 4 	0x34 	Power LED (blau) an
# 5 	0x35 	Power LED (blau) blinken (hoch/runterfahren)
# 6 	0x36 	Power LED aus
# 7 	0x37 	Status LED aus
# 8 	0x38 	Status LED grün an (Normalzustand)
# 9 	0x39 	Status LED grün blinkend (DSM nicht bereit)
# : 	0x3A 	Status LED orange an (?)
# ; 	0x3B 	Status LED orange blinkend (Fehler)
# @ 	0x40 	Copy LED an
# A 	0x41 	Copy LED blinkend
# B 	0x42 	Copy LED aus 

BEEP_SHORT=2
BEEP_LONG=3
# LED_POWER_FLASH=5
LED_STATUS_OFF=7
LED_STATUS_GREEN=8
LED_STATUS_GREEN_FLASH=9
LED_STATUS_ORANGE=:
LED_STATUS_ORANGE_FLASH=;
LED_COPY_ON=@
LED_COPY_FLASH=A
LED_COPY_OFF=B
NO_DSM_MESSAGE_RETURN_CODES=""

beep() {  # also used for LED control
  # requires root!
  /bin/echo "$1" > /dev/ttyS1
  #synoexternal  -susled disk_green/disk_orange/power none/steady/blink
}


beepError() {  # 3 times long beep
  beep 3
  /bin/sleep 1s
  beep 3
  /bin/sleep 1s
  beep 3
  /bin/sleep 1s
}

# Check whether file $1 exists: Result 0: yes, identical name, 1: upper/lower case is different, 2: no
# The -iname item of find command is not allowed to contain '/' ==> need to loop through path elements!
# not yet supported: multiple directories with same ignore-case-name

# shell option nocaseglob is only working for parts with wildcard!!!!!!
# https://unix.stackexchange.com/questions/16516/shopt-s-nocaseglob-is-not-working-on-ubuntu
# https://unix.stackexchange.com/questions/60162/how-to-make-cd-arguments-case-insensitive
findFileIgnoreCase() {
  if [[ -f "$1" ]]; then # if no support for possibly multiple results is required, e.g. log, Log, LOG this shortcut can be used!
    return 0 # identical
  fi
  filePath="$(dirname "$1")"
  fileName="$(basename "$1")"
  # echo "path='$filePath', name='$fileName'"
  if [[ "${filePath:0:1}" == "/" ]]; then
    file="/"
    filePath=${filePath:1}
    #echo "$filePath"
  else
    file=""
  fi
  mapfile -d "/" -t pathItems  < <(/bin/printf '%s' "$filePath") # if called from udev: /bin/ required for printf!!!
  # mapfile -d "/" -t pathItems  <<< "$filePath" # here string appends an newline to last element
  # pathItems[-1]=$(echo "${pathItems[-1]}" | sed -z 's|\n$||' ) # remove the \n which was appended to last item by "<<<"
  found=1
  #echo "path item count ${#pathItems[@]}"
  for ((i=0; i<${#pathItems[@]}; i+=1)); do # check path
    #echo "file='$file', item='${pathItems[$i]}':"
    res="$(find -L "$file" -maxdepth 1 -iname "${pathItems[$i]}" -type d)" # -L Follow symbolic links
    #echo "$file${pathItems[$i]}: res='$res'"
    if [[ -n "$res" ]]; then
      # missing here is the support for multiple results, e.g. log, Log, LOG
      file="$res/"
    else
      #echo "not existing"
      echo ""
      found=0
      break
    fi
  done
  if [[ "$found" -eq "1" ]]; then # check basename
    res="$(find "$file" -iname "$fileName" -type f)"
    if [[ -n "$res" ]]; then
      echo "$res"
      # missing here is the support for multiple results, e.g. log, Log, LOG
      if [[ "$res" == "$1" ]]; then
        return 0 # identical
      else
        return 1 # case different
      fi
    fi
  fi
  return 2 # not found
}


####################### start #############################
if [[ -z "$PATH" ]]; then
  PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/syno/bin:/usr/syno/sbin
fi
SCRIPTPATHTHIS="$( cd -- "$(/bin/dirname "$0")" >/dev/null 2>&1 ; /bin/pwd -P )" # e.g. /volumeX/@appstore/<app>
# echo "common: SCRIPTPATHTHIS='$SCRIPTPATHTHIS'"
# /volumeX/@appstore/<app>, not /var/packages/<app>/target (Link)
if [[ -n "${app_name}" ]]; then
  APPNAME="${app_name}"
else
  APPNAME=${SCRIPTPATHTHIS##*/} # APPNAME="UsbEject"
  # echo "common: APPNAME: '$APPNAME' extracted from script path"
  if [[ "$APPNAME" == "scripts" ]]; then # Why "scripts" if called from start-stop-status???
    # echo "common: APPNAME wrong: '$APPNAME'='scripts' !! ????"
    scriptpathParent=${SCRIPTPATHTHIS%/*}
    APPNAME=${scriptpathParent##*/} # APPNAME="UsbEject"
    # echo "common: APPNAME corrected: '$APPNAME'"
  fi
fi
APPDATA="/var/packages/$APPNAME/var" # appCfgDataPath="/var/packages/${app_name}/var"
LOGLEVEL=8 # preset, may be chanded in parse_hlp.sh from config 
# DTFMT="+%Y-%m-%d %H:%M:%S" # set in parse_hlp.sh

source "/var/packages/$APPNAME/target/ui/modules/parse_hlp.sh" #  logInfoNoEcho(), DTFMT, LOGLEVEL, urlencode(), urldecode()
SCRIPT_EXEC_LOG="$APPDATA/execLog"

# the LOGFILE may be set already different:
LOGFILEold=$LOGFILE
# echo "common: LOGFILEold=$LOGFILEold"
# source $scriptpathThis/bckCfg.txt # setup DsmNotifyClass, DsmNotifyCategory, DsmNotifyTitle, CcuIpAdrPort

source "$APPDATA/config"
if [[ -n "$LOGFILEold" ]]; then
  # echo "common: resetting LOGFILE from $LOGFILE (read from bckCfg.txt) to $LOGFILEold"
  LOGFILE=$LOGFILEold
fi
# echo "common LOGFILE='$LOGFILE'"
if [[ -z "$LOGFILE" ]]; then
  ## LOGFILE="/var/packages/UsbEject/target/log"
  # LOGFILE="$APPDATA/log" # equal to /volumeX/@appdata/<app>
  # LOGFILE="/var/log/packages/$APPNAME.log" # permission denied
  # /var/log/$APPNAME.log: Permission denied
  LOGFILE="/var/tmp/$APPNAME.log" # A link /var/packages/$SYNOPKG_PKGNAME/var/detailLog is set to this (see start-stop-status script)
  # echo "common LOGFILE changed, now='$LOGFILE'"
fi
LOG="$LOGFILE"
logInfo 7 "common ($0) was called with param1='$1', app_name='${app_name}', APPNAME='$APPNAME', APPDATA='$APPDATA', SCRIPTPATHTHIS='$SCRIPTPATHTHIS'"
lngUser=$SYNOPKG_DSM_LANGUAGE # not global DSM language but actual user language! Never 'def'
lngMail=$(/bin/get_key_value "/etc/synoinfo.conf" "maillang") # global setting, not individual user!
if [[ -z "$lngUser" ]]; then
  logInfo 5 "common: SYNOPKG_DSM_LANGUAGE is not available, trying maillang='$lngMail'"
  lngUser="$lngMail"  
fi
if [[ ! -f "/var/packages/$APPNAME/target/ui/texts/$lngUser/lang.txt" ]]; then
  logInfo 5 "common: /var/packages/$APPNAME/target/ui/texts/$lngUser/lang.txt not available, switched to enu"
  lngUser="enu"
fi

user=$(whoami) # EnvVar $USER may be not well set
  
logInfo 7 "common: user='$user', SYNOPKG_DSM_LANGUAGE='$SYNOPKG_DSM_LANGUAGE', lngMail='$lngMail', selected lngUser='$lngUser'"

